### ISSUE TITLE
raster ? 

### ISSUE THREAD

**Issue by charlottegermain** [r-bio/package-presentations#1]
Francois, 

I am not signed up for a presentation for a package, and I will not be able to get something together for the 10th, but I can present the package 'raster' on the 17th if some people are interested. If there is not enough interest, I will skip it, but if the demand is high, I am happy to take the time. 
I use raster a lot for map manipulation. 
Thanks
Charlotte

**Comment by fmichonneau** [comment]
That sounds good! I'll update the website shortly to reflect this. Thanks! :star:
